let money = 34973984;
console.log (typeof money);
let income = 'фриланс';
console.log (typeof income);
let addExpenses = 'Такси, Еда, Пивас';
let deposit = 7 === '7';
console.log (typeof deposit);
let mission = 343434343434;
let period = 7;
console.log (addExpenses.length);
console.log ("Период равен " + period + " месяцам");
console.log ("Цель заработать " + mission + " гривен");
console.log(addExpenses.toLowerCase(), addExpenses.split(', '));